export const categoryMeta = {
  Restaurant: { iconId: "food", key: "restaurant" },
  Café: { iconId: "cafe", key: "cafe" },
  Parc: { iconId: "tree", key: "outdoor" },
  Bibliothèque: { iconId: "books", key: "library" },
  Piscine: { iconId: "pool", key: "pool" },
  Musée: { iconId: "museum", key: "museum" },
  "Centre commercial": { iconId: "mall", key: "mall" },
  Activité: { iconId: "activity", key: "activity" },
};

export const filters = [
  { id: "changing_table", label: "Table à langer", iconId: "baby" },
  { id: "high_chair", label: "Chaise bébé", iconId: "chair" },
  { id: "play_corner", label: "Coin jeux", iconId: "play" },
  { id: "stroller", label: "Poussette OK", iconId: "stroller" },
  { id: "indoor", label: "Intérieur", iconId: "indoor" },
  { id: "outdoor", label: "Extérieur", iconId: "tree" },
  { id: "Restaurant", label: "Restaurant", iconId: "food" },
  { id: "Café", label: "Café", iconId: "cafe" },
  { id: "Activité", label: "Activité", iconId: "activity" },
];

export const places = [
  {
    id: "bbq-lille",
    name: "La Luck Lille",
    category: "Activité",
    address: "1 bis rue Princesse, Lille",
    phone: "03 20 15 78 31",
    website: "https://www.laluck.com",
    hours: "Mar-dim, 11:30-00:00",
    lat: 50.6448,
    lng: 3.0565,
    score: 92,
    distance: 1.1,
    photo: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=900&q=80",
    tags: ["indoor", "play_corner", "stroller"],
    equipment: [["activity", "Jeux de société enfants", 34], ["stroller", "Accessible poussette", 22], ["food", "Menu enfant", 18], ["indoor", "Intérieur", 41]],
    reviews: [
      { author: "Camille", age: "4-8 ans", welcome: 5, comfort: 4, gear: 4, text: "Equipe très patiente, jeux bien expliqués et tables faciles à partager." },
      { author: "Nassim", age: "6-10 ans", welcome: 5, comfort: 4, gear: 5, text: "Bon plan pluie, on peut vraiment rester longtemps sans stress." },
    ],
  },
  {
    id: "citadelle",
    name: "Parc de la Citadelle",
    category: "Parc",
    address: "Avenue du 43e Régiment d'Infanterie, Lille",
    phone: "03 20 49 50 00",
    website: "https://www.lille.fr",
    hours: "Tous les jours",
    lat: 50.641,
    lng: 3.044,
    score: 88,
    distance: 1.6,
    photo: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=900&q=80",
    tags: ["outdoor", "play_corner", "stroller"],
    equipment: [["play", "Aires de jeux", 67], ["stroller", "Accessible poussette", 53], ["tree", "Espace extérieur", 82], ["picnic", "Pique-nique facile", 29]],
    reviews: [
      { author: "Lucie", age: "0-10 ans", welcome: 4, comfort: 4, gear: 4, text: "Grand espace, chemins praticables et beaucoup de pauses possibles." },
      { author: "Sarah", age: "2-6 ans", welcome: 4, comfort: 5, gear: 4, text: "Très pratique avec draisienne et poussette, surtout le matin." },
    ],
  },
  {
    id: "cafemome",
    name: "Café Môme",
    category: "Café",
    address: "Rue Esquermoise, Lille",
    phone: "03 20 00 00 00",
    website: "https://example.com",
    hours: "Lun-sam, 09:00-18:30",
    lat: 50.6372,
    lng: 3.0615,
    score: 79,
    distance: 0.5,
    photo: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80",
    tags: ["indoor", "changing_table", "high_chair", "stroller"],
    equipment: [["baby", "Table à langer", 16], ["chair", "Chaise bébé", 21], ["stroller", "Accessible poussette", 12], ["bottle", "Chauffe biberon", 8]],
    reviews: [
      { author: "Aline", age: "0-3 ans", welcome: 5, comfort: 4, gear: 4, text: "Petit mais vraiment accueillant, table à langer confirmée." },
      { author: "Jules", age: "1-4 ans", welcome: 4, comfort: 4, gear: 3, text: "Service sympa, mieux hors heure de pointe avec une poussette." },
    ],
  },
  {
    id: "lam",
    name: "LaM",
    category: "Musée",
    address: "1 allée du Musée, Villeneuve-d'Ascq",
    phone: "03 20 19 68 68",
    website: "https://www.musee-lam.fr",
    hours: "Mar-dim, 10:00-18:00",
    lat: 50.6377,
    lng: 3.1502,
    score: 84,
    distance: 7.2,
    photo: "https://images.unsplash.com/photo-1544967082-d9d25d867d66?auto=format&fit=crop&w=900&q=80",
    tags: ["indoor", "outdoor", "stroller", "activity"],
    equipment: [["stroller", "Accessible poussette", 38], ["sparkle", "Ateliers enfants", 26], ["tree", "Jardin de sculptures", 19], ["indoor", "Intérieur", 40]],
    reviews: [
      { author: "Marion", age: "5-10 ans", welcome: 5, comfort: 4, gear: 4, text: "Ateliers très adaptés, bonne circulation dans les salles." },
      { author: "Thomas", age: "3-7 ans", welcome: 4, comfort: 4, gear: 4, text: "Le jardin aide à faire une pause entre deux salles." },
    ],
  },
  {
    id: "mediatheque-lomme",
    name: "Médiathèque de Lomme",
    category: "Bibliothèque",
    address: "794 avenue de Dunkerque, Lomme",
    phone: "03 20 17 27 40",
    website: "https://bm-lille.fr",
    hours: "Mar-sam",
    lat: 50.6436,
    lng: 3.0124,
    score: 73,
    distance: 4.1,
    photo: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=900&q=80",
    tags: ["indoor", "stroller", "play_corner"],
    equipment: [["books", "Espace jeunesse", 24], ["stroller", "Accessible poussette", 18], ["play", "Coin lecture enfants", 14], ["indoor", "Intérieur", 23]],
    reviews: [{ author: "Inès", age: "2-8 ans", welcome: 4, comfort: 4, gear: 3, text: "Calme, lumineux, bon espace jeunesse." }],
  },
  {
    id: "euralille",
    name: "Westfield Euralille",
    category: "Centre commercial",
    address: "100 avenue Willy Brandt, Lille",
    phone: "03 20 14 52 20",
    website: "https://www.westfield.com/france/euralille",
    hours: "Lun-sam, 10:00-20:00",
    lat: 50.638,
    lng: 3.075,
    score: 68,
    distance: 1.0,
    photo: "https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?auto=format&fit=crop&w=900&q=80",
    tags: ["indoor", "changing_table", "stroller"],
    equipment: [["baby", "Table à langer", 31], ["stroller", "Accessible poussette", 44], ["indoor", "Intérieur", 50], ["wheelchair", "Ascenseurs", 28]],
    reviews: [{ author: "Amel", age: "0-6 ans", welcome: 3, comfort: 4, gear: 4, text: "Pratique en dépannage, attention aux heures très chargées." }],
  },
  {
    id: "piscine-marx",
    name: "Piscine Marx Dormoy",
    category: "Piscine",
    address: "36 avenue Marx Dormoy, Lille",
    phone: "03 20 92 53 30",
    website: "https://www.lille.fr",
    hours: "Selon créneaux",
    lat: 50.6321,
    lng: 3.0472,
    score: 58,
    distance: 2.2,
    photo: "https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=900&q=80",
    tags: ["indoor", "changing_table"],
    equipment: [["baby", "Table à langer", 9], ["pool", "Bassin enfant", 12], ["indoor", "Intérieur", 16]],
    reviews: [{ author: "Paul", age: "3-8 ans", welcome: 3, comfort: 3, gear: 3, text: "Bassin agréable, vestiaires parfois serrés avec enfants." }],
  },
  {
    id: "ferme-marcel",
    name: "La Ferme Marcel Dhénin",
    category: "Activité",
    address: "14 rue Eugène Jacquet, Lille",
    phone: "03 20 55 16 12",
    website: "https://www.lille.fr",
    hours: "Mer-dim",
    lat: 50.6416,
    lng: 3.0837,
    score: 95,
    distance: 1.8,
    photo: "https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&w=900&q=80",
    tags: ["outdoor", "activity", "stroller"],
    equipment: [["activity", "Activités enfants", 45], ["tree", "Espace extérieur", 39], ["stroller", "Accessible poussette", 23], ["water", "Point d'eau", 17]],
    reviews: [{ author: "Zoé", age: "1-8 ans", welcome: 5, comfort: 5, gear: 4, text: "Très vivant, parfait pour une sortie courte sans quitter Lille." }],
  },
];

export const boards = {
  week: [["Camille", "128 pts", "Explorateur"], ["Nassim", "96 pts", "Chasseur de pépites"], ["Sarah", "74 pts", "Parent Expert"]],
  month: [["Lucie", "420 pts", "Ambassadeur Lille"], ["Aline", "344 pts", "Parent Expert"], ["Marion", "310 pts", "Explorateur"]],
  global: [["Lille Family", "2 840 pts", "Ambassadeur Lille"], ["Team Lomme", "1 990 pts", "Parent Expert"], ["MEL Kids", "1 720 pts", "Chasseur de pépites"]],
};
